kind: pipeline
name: default

steps:

  - name: build
    image: golang:alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - apk --no-cache add git
      - go mod tidy
      - go build -o dronetrigger-linux-amd64 .

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dronetrigger-linux-amd64
      checksum:
        - md5
        - sha1
        - sha256
    when:
      event: tag
